app = "scroll-press"
primary_region = "fra"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8000"
  PYTHONPATH = "."

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  max_machines_running = 5
  processes = ["app"]
  
  # Autoscaling configuration for 100 concurrent users
  [http_service.concurrency]
    type = "requests"
    soft_limit = 75
    hard_limit = 100

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[deploy]
  release_command = "uv run alembic upgrade head"

  # Health checks for http_service
  [[http_service.checks]]
    grace_period = "10s"
    interval = "15s"
    method = "GET"
    path = "/health"
    protocol = "http"
    timeout = "3s"
