"""Add license field to scrolls table

Revision ID: 23c7a3d4442f
Revises: 2c44b55a3bd6
Create Date: 2025-08-01 21:43:44.279848

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "23c7a3d4442f"
down_revision: Union[str, Sequence[str], None] = "2c44b55a3bd6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add license field as nullable first
    op.add_column("scrolls", sa.Column("license", sa.String(length=20), nullable=True))

    # Set all existing scrolls to CC BY 4.0 as specified in requirements
    op.execute("UPDATE scrolls SET license = 'cc-by-4.0' WHERE license IS NULL")

    # Now make the field non-nullable
    op.alter_column("scrolls", "license", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("scrolls", "license")
    # ### end Alembic commands ###
