"""Add last_accessed_at to scrolls

Revision ID: 3f51169c08c8
Revises: 1814fddc9a60
Create Date: 2026-02-10 06:28:01.370402

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3f51169c08c8"
down_revision: Union[str, Sequence[str], None] = "1814fddc9a60"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column as nullable first, then set defaults and make it not null
    op.add_column(
        "scrolls", sa.Column("last_accessed_at", sa.DateTime(timezone=True), nullable=True)
    )

    # Set existing rows to use created_at as the initial value
    op.execute("UPDATE scrolls SET last_accessed_at = created_at WHERE last_accessed_at IS NULL")

    # Now make it not nullable
    op.alter_column("scrolls", "last_accessed_at", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("scrolls", "last_accessed_at")
    # ### end Alembic commands ###
