"""add_preview_status_validation

Revision ID: c2f3c0831df3
Revises: b4c9a0f2a445
Create Date: 2026-01-24 10:48:34.943828

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "c2f3c0831df3"
down_revision: Union[str, Sequence[str], None] = "b4c9a0f2a445"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
