"""add tokens table for email verification and password reset

Revision ID: ffb0fc228185
Revises: f7ed1e1bdfde
Create Date: 2026-01-01 22:53:12.409687

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op
from app.models.user import GUID

# revision identifiers, used by Alembic.
revision: str = "ffb0fc228185"
down_revision: Union[str, Sequence[str], None] = "f7ed1e1bdfde"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tokens",
        sa.Column("id", GUID(), nullable=False),
        sa.Column("user_id", GUID(), nullable=False),
        sa.Column("token", sa.String(length=64), nullable=False),
        sa.Column("token_type", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_tokens_expires_at", "tokens", ["expires_at"], unique=False)
    op.create_index("idx_tokens_token", "tokens", ["token"], unique=False)
    op.create_index("idx_tokens_user_id", "tokens", ["user_id"], unique=False)
    op.create_index(op.f("ix_tokens_expires_at"), "tokens", ["expires_at"], unique=False)
    op.create_index(op.f("ix_tokens_token"), "tokens", ["token"], unique=True)
    op.create_index(op.f("ix_tokens_user_id"), "tokens", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tokens_user_id"), table_name="tokens")
    op.drop_index(op.f("ix_tokens_token"), table_name="tokens")
    op.drop_index(op.f("ix_tokens_expires_at"), table_name="tokens")
    op.drop_index("idx_tokens_user_id", table_name="tokens")
    op.drop_index("idx_tokens_token", table_name="tokens")
    op.drop_index("idx_tokens_expires_at", table_name="tokens")
    op.drop_table("tokens")
    # ### end Alembic commands ###
