name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: press
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        enable-cache: true

    - name: Install dependencies
      run: uv sync

    - name: Install Just
      uses: extractions/setup-just@v1

    - name: Cache Playwright browsers
      uses: actions/cache@v4
      id: playwright-cache
      with:
        path: ~/.cache/ms-playwright
        key: ${{ runner.os }}-playwright-${{ hashFiles('uv.lock') }}

    - name: Install Playwright browsers
      if: steps.playwright-cache.outputs.cache-hit != 'true'
      run: uv run playwright install --with-deps

    - name: Run database migrations
      env:
        DATABASE_URL: postgresql+asyncpg://postgres:password@localhost:5432/press
        TESTING: 1
      run: uv run alembic upgrade head

    - name: Seed database with test data
      env:
        DATABASE_URL: postgresql+asyncpg://postgres:password@localhost:5432/press
        TESTING: 1
        PYTHONPATH: .
      run: |
        echo "Seeding database..."
        uv run python app/seed.py
        echo "Waiting for seeding to complete..."
        sleep 2

    - name: Run linting
      run: just lint

    - name: Run unit tests
      env:
        DATABASE_URL: postgresql+asyncpg://postgres:password@localhost:5432/press
        TESTING: 1
      run: uv run pytest -m "not e2e"

    - name: Start development server for e2e tests
      env:
        DATABASE_URL: postgresql+asyncpg://postgres:password@localhost:5432/press
        TESTING: 1
        PYTHONPATH: .
        PORT: 8000
      run: |
        echo "Starting FastAPI server for e2e tests..."
        uv run uvicorn main:app --host 0.0.0.0 --port 8000 --log-level info &
        echo "Waiting for server to start..."
        sleep 8
        echo "Testing server connection..."
        curl -f http://localhost:8000 || exit 1
        echo "Server is ready for e2e tests"

    - name: Run desktop e2e tests
      env:
        DATABASE_URL: postgresql+asyncpg://postgres:password@localhost:5432/press
        TESTING: 1
      run: |
        echo "Running desktop-specific E2E tests..."
        timeout 120 uv run pytest -m "e2e and desktop" --tb=short -v || echo "Desktop E2E tests completed with issues"

    - name: Run mobile e2e tests - WebKit (iOS Safari)
      env:
        DATABASE_URL: postgresql+asyncpg://postgres:password@localhost:5432/press
        TESTING: 1
      run: |
        echo "Running mobile E2E tests with WebKit (iOS Safari emulation)..."
        timeout 120 uv run pytest -m "e2e and mobile" --tb=short -v --browser webkit || echo "Mobile WebKit E2E tests completed with issues"

    - name: Run mobile e2e tests - Chromium (Android)
      env:
        DATABASE_URL: postgresql+asyncpg://postgres:password@localhost:5432/press
        TESTING: 1
      run: |
        echo "Running mobile E2E tests with Chromium (Android emulation)..."
        timeout 120 uv run pytest -m "e2e and mobile" --tb=short -v --browser chromium || echo "Mobile Chromium E2E tests completed with issues"

    - name: Run universal e2e tests
      env:
        DATABASE_URL: postgresql+asyncpg://postgres:password@localhost:5432/press
        TESTING: 1
      run: |
        echo "Running universal E2E tests (work on both desktop and mobile)..."
        timeout 120 uv run pytest -m "e2e and not desktop and not mobile" --tb=short -v || echo "Universal E2E tests completed with issues"
